authnapp/urls.py
from django.urls import path
import authnapp.views as authnapp

app_name = 'authnapp'

urlpatterns = [
    path('login/', authnapp.login, name='login'),
    path('logout/', authnapp.logout, name='logout'),
    path('register/', authnapp.register, name='register'),
    path('edit/', authnapp.edit, name='edit')
]

basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path("", basketapp.basket, name="view"),
    path("add/<int:pk>/", basketapp.basket_add, name="add"),
    path("remove/<int:pk>/", basketapp.basket_remove, name="remove"),
    # path("edit/<int:pk>/<int:quantity>/", basketapp.basket_edit, name="edit"),
]

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   path('', mainapp.products, name='index'),
   path('category/<int:pk>/', mainapp.products, name='category'),
   path('product/<int:pk>/', mainapp.product, name='product'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include("authnapp.urls", namespace='auth')),
    path('basket/', include("basketapp.urls", namespace="basket"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __set__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='product_img', blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='кол-во на складе', default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"


class Contact(models.Model):
    phone = models.CharField(max_length=32, verbose_name='номер телефона')
    email = models.EmailField(max_length=128, verbose_name='email')
    city = models.CharField(max_length=32, default='Москва', verbose_name='город')
    address = models.CharField(max_length=128, verbose_name='адрес')

    def __str__(self):
        return f"{self.pk} {self.email}"

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import ProductCategory, Product, Contact
from basketapp.models import Basket
from django.conf import settings
from django.utils import timezone
import random


def main(request):
    title = "Главная"
    all_products = Product.objects.all()[:2]
    content = {"title": title, "products": all_products}
    return render(request, "mainapp/index.html", context=content)


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).\
                                    exclude(pk=hot_product.pk)[:3]
    return same_products


def products(request, pk=None):
    title = "Продукты"
    links_menu = ProductCategory.objects.all()
    # slider_products = [
    #     {"img": "prod-2.jpg"},
    #     {"img": "prod-3.jpg"},
    #     {"img": "prod-4.jpg"},
    # ]
    basket = get_basket(request.user)

    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by("price")
            category = {"name": "все"}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by("price")

        content = {
            "title": title,
            "links_menu": links_menu,
            "category": category,
            "products": products,
            "basket": basket,
        }
        return render(request, "mainapp/products_list.html", content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
        'basket': basket,
    }

    return render(request, 'mainapp/products.html', content)


def product(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
    }

    return render(request, 'mainapp/product.html', content)


def contact(request):
    title = "о нас"
    visit_date = timezone.now()
    locations = Contact.objects.all()
    content = {"title": title, "visit_date": visit_date, "locations": locations}
    return render(request, "mainapp/contact.html", context=content)

mainapp/templates/mainapp/includes/inc_categories_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li>
            <a href="{% url 'products:category' 0 %}"
               class="{% if request.resolver_match.kwargs.pk == '0' %}
                    active
                {% endif %}">
                все
            </a>
        </li>
        {% for link in links_menu %}
            <li>
            <a href="{% url 'products:category' link.pk %}"
                class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
                      active
                 {% endif %}">

                {{ link.name }}
            </a>
            </li>
        {% endfor %}
    </ul>
</div>

mainapp/templates/mainapp/includes/inc_menu.html
<a href="/" class="logo"></a>
    <ul class="menu">
        <li><a href="{% url 'main' %}"
               class="{% if request.resolver_match.url_name == 'main' %}active{% endif %}">домой</a></li>
        <li><a href="{% url 'products:index' %}"
               class="{% if request.resolver_match.namespace == 'products' %}active{% endif %}">продукты</a></li>
        <li><a href="{% url 'contact' %}"
               class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">контакты</a></li>
        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'auth:edit' %}">
                {{ user.first_name|default:'Личный кабинет' }}
            </a>
        </li>
        {% else %}
        <li>
            <a href="{% url 'auth:register' %}">регистрация</a>
        </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">выйти</a>
            {% else %}
            <a href="{% url 'auth:login' %}">войти</a>
            {% endif %}
        </li>
    </ul>
<a href="#" class="search"></a>
<a href="{% url 'basket:view' %}" class="basket">
    <span class="basket_cnt_price">
        {% if basket %}
             {{ basket.0.total_cost|floatformat:0 }}&#8381
             {{ basket.0.total_quantity }} шт
        {% endif %}
    </span>
</a>