basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path("", basketapp.basket, name="view"),
    path("add/<int:pk>/", basketapp.basket_add, name="add"),
    path("remove/<int:pk>/", basketapp.basket_remove, name="remove"),
    # path("edit/<int:pk>/<int:quantity>/", basketapp.basket_edit, name="edit"),
]

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   path('', mainapp.products, name='index'),
   path('category/<int:pk>/', mainapp.products, name='category'),
   path('product/<int:pk>/', mainapp.product, name='product'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include("authnapp.urls", namespace='auth')),
    path('basket/', include("basketapp.urls", namespace="basket"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __set__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='product_img', blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='кол-во на складе', default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"


class Contact(models.Model):
    phone = models.CharField(max_length=32, verbose_name='номер телефона')
    email = models.EmailField(max_length=128, verbose_name='email')
    city = models.CharField(max_length=32, default='Москва', verbose_name='город')
    address = models.CharField(max_length=128, verbose_name='адрес')

    def __str__(self):
        return f"{self.pk} {self.email}"

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import ProductCategory, Product, Contact
from basketapp.models import Basket
from django.conf import settings
from django.utils import timezone
import random


def main(request):
    title = "Главная"
    all_products = Product.objects.all()[:2]
    content = {"title": title, "products": all_products}
    return render(request, "mainapp/index.html", context=content)


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).\
                                    exclude(pk=hot_product.pk)[:3]
    return same_products


def products(request, pk=None):
    title = "Продукты"
    links_menu = ProductCategory.objects.all()
    # slider_products = [
    #     {"img": "prod-2.jpg"},
    #     {"img": "prod-3.jpg"},
    #     {"img": "prod-4.jpg"},
    # ]
    basket = get_basket(request.user)

    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by("price")
            category = {"name": "все"}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by("price")

        content = {
            "title": title,
            "links_menu": links_menu,
            "category": category,
            "products": products,
            "basket": basket,
        }
        return render(request, "mainapp/products_list.html", content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
        'basket': basket,
    }

    return render(request, 'mainapp/products.html', content)


def product(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
    }

    return render(request, 'mainapp/product.html', content)


def contact(request):
    title = "о нас"
    visit_date = timezone.now()
    locations = Contact.objects.all()
    content = {"title": title, "visit_date": visit_date, "locations": locations}
    return render(request, "mainapp/contact.html", context=content)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<!--<html lang="en">-->
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ title }}
        {% endblock title %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
	    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock css %}

    {% block js %}
    {% endblock js %}
</head>
<body>
    <div class="container">

        {% block menu %}
        {% endblock menu %}

        <div class="content">
            {% block content %}
            {% endblock content %}
        </div>

    </div>

    {% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB {% now "Y.m" %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
    </div>
    {% endblock footer %}

</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
	<div class="container">
		<div class="hero">
			<div class="header clearfix">

				{% include 'mainapp/includes/inc_menu.html' %}

			</div>
			<h1>наши контакты</h1>
			<p>сегодня: {{ visit_date|date:"l, j F, Y" }}</p>
		</div>
	</div>
{% endblock menu %}
{% block content %}
		<div class="location">
			{% for location in locations %}
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>{{location.city}}</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>{{location.phone}}</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>{{location.email}}</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>{{location.address}}</p>
				</div>
			</div>
			{% endfor %}
		</div>

		<div class="clr"></div>
{% endblock content %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
	<div class="container">
		<div class="slider">
			<div class="header clearfix">
				{% include 'mainapp/includes/inc_menu.html' %}
			</div>
			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
			</div>	
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>
	</div>
{% endblock menu %}
{% block content %}
		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				{% for prod in products %}
				<div class="block">
					<a href="#"><img src="/media/{{prod.image}}" alt="" width="270", height="270">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="img">
							<h4>{{prod.category.name|upper}}</h4>
							<h4>{{prod.name|upper}}</h4>
							<p>{{prod.description}}</p>
						</div> 
					</a>
				</div>
				{% endfor %}
			</div>
		</div>
		
		<div class="clr"></div>
{% endblock content %}


mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
<body>
	<div class="container">
		<div class="hero-white">
			<div class="header clearfix">

				{% include 'mainapp/includes/inc_menu.html' %}

			</div>
		</div>
	</div>
{% endblock menu %}

{% block content %}
  <div class="details">

      {% include 'mainapp/includes/inc_categories_menu.html' %}

    <div class="details-products">
      <div class="details-slider">
        <div class="slider-product">
          <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}" width="550" height="550">
        </div>
        <div class="slider-control">
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 1" width="100" height="100">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 2" width="100" height="100">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/{{ product.image }}" alt="вариант 3" width="100" height="100">
            </a>
          </div>
        </div>
      </div>

      <div class="description">
        <h3 class="big-bold">{{ product.name|upper }}</h3>
        <br><br>
        <p class="price"> {{ product.price }} <span>руб</span></p>
        <a href="{% url 'basket:add' product.pk %}" class="red-button">
          заказать
          <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
          {{ product.description }}
        </div>
      </div>
    </div>

  </div>

  <div class="clr"></div>
{% endblock content %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static%}

{% block menu %}
<body>
	<div class="container">
		<div class="hero-white">
			<div class="header clearfix">

				{% include 'mainapp/includes/inc_menu.html' %}

			</div>
		</div>
	</div>
{% endblock menu %}
{% block content %}
		<div class="details">

			{% include 'mainapp/includes/inc_categories_menu.html' %}

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
					  <img src="/media/{{ hot_product.image }}" width="550" height="550">
					</div>
					<div class="slider-control">
					  	<div class="block">
							<a href="#"><img src="/media/{{ hot_product.image }}" width="100" height="100" alt=""></a>
					  	</div>
					  	<div class="block">
							<a href="#"><img src="/media/{{ hot_product.image }}" width="100" height="100" alt=""></a>
					  	</div>
					  	<div class="block">
							<a href="#"><img src="/media/{{ hot_product.image }}" width="100" height="100" alt=""></a>
					  	</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">{{ hot_product.name }}</h3>
					<h3 class="red">горячее предложение*</h3>
					<p class="price">{{ hot_product.price }} <span>руб</span></p>
					<a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						{{ hot_product.description }}
						<p>* предложение действительно до {% now "Y-m-d"%}</p>
					</div>
				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">
					{% for prod in same_products %}
					<div class="block">
						<a href="#"><img src="/media/{{prod.image}}" alt="{{same_prod.name}}">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>{{prod.name}}</h4>
								<p>{{prod.description}}</p>
								<p>Цена: {{ prod.price }} </p>
                        		<p>На складе: {{ prod.quantity }} </p>
							</div>
						</a>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>

		<div class="clr"></div>

{% endblock content %}

mainapp/templates/mainapp/products_list.html
{% extends "mainapp/products.html" %}
{% load static %}

{% block menu %}
<body>
	<div class="container">
		<div class="hero-white">
			<div class="header clearfix">

				{% include 'mainapp/includes/inc_menu.html' %}

			</div>
		</div>
	</div>
{% endblock menu %}

{% block content %}
    <div class="details">
        {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="related">
        <div class="title clearfix">
            <h2> Категория: "{{ category.name|title }}" </h2>
        </div>

        <div class="related-products clearfix">
            {% for prod in products %}
            <div class="block">
                <a href="{% url 'products:product' prod.pk %}">
                    <img src="/media/{{ prod.image }}" alt="product">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                        <h4>{{prod.name}}</h4>
                        <p> {{prod.description}}</p>
                        <p> Цена: {{ prod.price }} </p>
                        <p> На складе: {{ prod.quantity }} </p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="clr"></div>

{% endblock content%}